name: Daily Commit for GitHub Activity

on:
 schedule:
  - cron: '17 12 * * *' # runs at 12:30 PM UTC
  workflow_dispatch: # Allow manual run from GitHub UI

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Auto Commit
      run: |
        echo "Update: $(date)" >> activity.log
        git config --global user.name "YourGitHubUsername"
        git config --global user.email "youremail@example.com"
        git add activity.log
        git commit -m "chore: daily activity log - $(date)" || echo "Nothing to commit"
        git push
